"""empty message

Revision ID: 53edf1ae1193
Revises: 
Create Date: 2025-08-17 23:19:49.059511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53edf1ae1193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propietario',
    sa.Column('codigo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('codigo_id'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propietario')
    # ### end Alembic commands ###
